python:                        # [win]
  - 3.8                        # [win]
c_compiler:                    # [win]  
  - vs2015                     # [win]
cxx_compiler:                  # [win]
  - vs2015                     # [win]
vc:                            # [win]   
  - 14.1                       # [win] 
