travis:
  secure:
    BINSTAR_TOKEN: IDU7ACOdD7+UlxfPopnd0EUiRfucjRTQMaznApldoxFqUmEo+AQ8P32zfU+UncNLPvPgeOAD1YRiDSo67XBfmkxCwNW1pRa7R+AKD5iLZUPLbi2S0KlAjciWyKScboAcLS6w2kezveBIWy2ew2vnLLUzMafbIo3It3F2R9y/nJSludmzQ2GdZ81zpgCwV3TD9URFEAkqDO2MmCI06WKslqvFp/8rfNUfyt/NeIaCZqiseTa2lY3kdhk9ULOptIEOAAWtNYdDMdl/ueLaMPcJkSC6hLjZNZWg6HMLI5BRb79ocX7joGBDdUKh6zqDnAd5cHvvZDrRjbzls3Ue4Z4kdxg3YzuFz1rUZuM6taN/e9kSAm3YqYg4H0neQL3DenenHGUwlrLsA4kYBmAWRXkykbtGUP6WWdTzqyTUwzikIdsAmK/a4ifwdVumq/w7qZ1zY+Fi9YysSRzJScvxfAC5b/ZpQSghRIV+P+HKUaEZzOUO/v2LoiBzfJIQ+tnmJ711wOh4Jjm/EuGbV3tncFgbwLU6ui5gGDPacHMgZKmbY2pDZ4bbwz+nJ9GfSJcvJxZtbCcn4QSh2MJblrf24Lv9Gn8b+EGe0mwuTvDf+5wo4L2EZxpkkkAP7mMaRAQe+VOCwHHkYNXdCHfqQFqxLoGt08FPn6cKD3mdaenGr51tqoA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
